// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: behaviors.sql

package database

import (
	"context"
)

const getBehaviorsOfClient = `-- name: GetBehaviorsOfClient :many
SELECT cst_dim_id, transdate, monthly_os_changes, monthly_phone_model_changes, last_phone_model_categorical, last_os_categorical, logins_last_7_days, logins_last_30_days, login_frequency_7d, freq_change_7d_vs_mean, logins_7d_over_30d_ratio, avg_login_interval_30d, std_login_interval_30d, var_login_interval_30d, ewm_login_interval_7d, burstiness_login_interval, fano_factor_login_interval, zscore_avg_login_interval_7d FROM behaviors 
WHERE cst_dim_id = ?
`

func (q *Queries) GetBehaviorsOfClient(ctx context.Context, cstDimID int64) ([]Behavior, error) {
	rows, err := q.db.QueryContext(ctx, getBehaviorsOfClient, cstDimID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Behavior
	for rows.Next() {
		var i Behavior
		if err := rows.Scan(
			&i.CstDimID,
			&i.Transdate,
			&i.MonthlyOsChanges,
			&i.MonthlyPhoneModelChanges,
			&i.LastPhoneModelCategorical,
			&i.LastOsCategorical,
			&i.LoginsLast7Days,
			&i.LoginsLast30Days,
			&i.LoginFrequency7d,
			&i.FreqChange7dVsMean,
			&i.Logins7dOver30dRatio,
			&i.AvgLoginInterval30d,
			&i.StdLoginInterval30d,
			&i.VarLoginInterval30d,
			&i.EwmLoginInterval7d,
			&i.BurstinessLoginInterval,
			&i.FanoFactorLoginInterval,
			&i.ZscoreAvgLoginInterval7d,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
