// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package database

import (
	"context"
)

const getClientByCstDimId = `-- name: GetClientByCstDimId :one

SELECT cst_dim_id, first_name, last_name, gender FROM clients 
WHERE cst_dim_id = ?
`

func (q *Queries) GetClientByCstDimId(ctx context.Context, cstDimID int64) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByCstDimId, cstDimID)
	var i Client
	err := row.Scan(
		&i.CstDimID,
		&i.FirstName,
		&i.LastName,
		&i.Gender,
	)
	return i, err
}

const getClients = `-- name: GetClients :many
SELECT cst_dim_id, first_name, last_name, gender FROM clients
`

func (q *Queries) GetClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, getClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.CstDimID,
			&i.FirstName,
			&i.LastName,
			&i.Gender,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
