// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: codes.sql

package database

import (
	"context"
)

const confirmCode = `-- name: ConfirmCode :exec

UPDATE codes
SET updated_at = CURRENT_TIMESTAMP,
    confirmed = 'TRUE'
WHERE email = ? AND created_at = ?
`

type ConfirmCodeParams struct {
	Email     string
	CreatedAt string
}

func (q *Queries) ConfirmCode(ctx context.Context, arg ConfirmCodeParams) error {
	_, err := q.db.ExecContext(ctx, confirmCode, arg.Email, arg.CreatedAt)
	return err
}

const createCode = `-- name: CreateCode :exec
INSERT INTO codes(email, code)
VALUES (?, ?)
`

type CreateCodeParams struct {
	Email string
	Code  string
}

func (q *Queries) CreateCode(ctx context.Context, arg CreateCodeParams) error {
	_, err := q.db.ExecContext(ctx, createCode, arg.Email, arg.Code)
	return err
}

const getCodeOfUser = `-- name: GetCodeOfUser :one

SELECT email, created_at, updated_at, code, confirmed FROM codes
WHERE email = ? AND
    confirmed = 'FALSE' AND
    created_at > DATETIME('now', '-5 minutes')
ORDER BY created_at DESC
`

func (q *Queries) GetCodeOfUser(ctx context.Context, email string) (Code, error) {
	row := q.db.QueryRowContext(ctx, getCodeOfUser, email)
	var i Code
	err := row.Scan(
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Code,
		&i.Confirmed,
	)
	return i, err
}

const getCodesOfUser = `-- name: GetCodesOfUser :many

SELECT email, created_at, updated_at, code, confirmed FROM codes
WHERE email = ?
ORDER BY created_at DESC
`

func (q *Queries) GetCodesOfUser(ctx context.Context, email string) ([]Code, error) {
	rows, err := q.db.QueryContext(ctx, getCodesOfUser, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Code
	for rows.Next() {
		var i Code
		if err := rows.Scan(
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Code,
			&i.Confirmed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
