// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Client struct {
	CstDimID  int64
	FirstName string
	LastName  string
	Gender    string
}

type Code struct {
	Email     string
	CreatedAt string
	UpdatedAt string
	Code      string
	Confirmed string
}

type RefreshToken struct {
	Token     string
	CreatedAt string
	Email     string
	ExpiresAt string
	RevokedAt sql.NullString
}

type User struct {
	Email        string
	CreatedAt    string
	UpdatedAt    string
	PasswordHash string
	FirstName    string
	LastName     string
}
