// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Behavior struct {
	CstDimID                  int64
	Transdate                 string
	MonthlyOsChanges          int64
	MonthlyPhoneModelChanges  int64
	LastPhoneModelCategorical string
	LastOsCategorical         string
	LoginsLast7Days           int64
	LoginsLast30Days          int64
	LoginFrequency7d          float64
	FreqChange7dVsMean        float64
	Logins7dOver30dRatio      float64
	AvgLoginInterval30d       float64
	StdLoginInterval30d       float64
	VarLoginInterval30d       float64
	EwmLoginInterval7d        float64
	BurstinessLoginInterval   float64
	FanoFactorLoginInterval   float64
	ZscoreAvgLoginInterval7d  float64
}

type Client struct {
	CstDimID  int64
	FirstName string
	LastName  string
	Gender    string
}

type Code struct {
	Email     string
	CreatedAt string
	UpdatedAt string
	Code      string
	Confirmed string
}

type RefreshToken struct {
	Token     string
	CreatedAt string
	Email     string
	ExpiresAt string
	RevokedAt sql.NullString
}

type Transaction struct {
	CstDimID      int64
	Transdatetime string
	Transdate     string
	Amount        int64
	Direction     string
	Target        int64
}

type User struct {
	Email        string
	CreatedAt    string
	UpdatedAt    string
	PasswordHash string
	FirstName    string
	LastName     string
}
