// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package database

import (
	"context"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens(token, email, expires_at)
VALUES (?, ?, ?)
`

type CreateRefreshTokenParams struct {
	Token     string
	Email     string
	ExpiresAt string
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken, arg.Token, arg.Email, arg.ExpiresAt)
	return err
}

const getRefreshTokenOfUser = `-- name: GetRefreshTokenOfUser :one

SELECT token FROM refresh_tokens
WHERE email = ?
    AND revoked_at IS NULL
    AND expires_at > CURRENT_TIMESTAMP
ORDER BY created_at DESC
`

func (q *Queries) GetRefreshTokenOfUser(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenOfUser, email)
	var token string
	err := row.Scan(&token)
	return token, err
}

const getUserFromRefreshToken = `-- name: GetUserFromRefreshToken :one

SELECT users.email, users.created_at, users.updated_at, users.password_hash, users.first_name, users.last_name FROM users
JOIN refresh_tokens ON users.email = refresh_tokens.email
WHERE refresh_tokens.token = ?
    AND revoked_at IS NULL
    AND expires_at > CURRENT_TIMESTAMP
ORDER BY created_at DESC
`

func (q *Queries) GetUserFromRefreshToken(ctx context.Context, token string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserFromRefreshToken, token)
	var i User
	err := row.Scan(
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const revokeToken = `-- name: RevokeToken :exec

UPDATE refresh_tokens
SET updated_at = CURRENT_TIMESTAMP, revoked_at = CURRENT_TIMESTAMP
WHERE token = ? AND revoked_at IS NULL
`

func (q *Queries) RevokeToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeToken, token)
	return err
}
