// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package database

import (
	"context"
	"database/sql"
)

const getTransactions = `-- name: GetTransactions :many
SELECT  c.first_name, c.last_name, 
    t.transdatetime, t.amount, t.direction, t.target 
    FROM transactions AS t
LEFT JOIN clients AS c
ON t.cst_dim_id = c.cst_dim_id
`

type GetTransactionsRow struct {
	FirstName     sql.NullString
	LastName      sql.NullString
	Transdatetime string
	Amount        int64
	Direction     string
	Target        int64
}

func (q *Queries) GetTransactions(ctx context.Context) ([]GetTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsRow
	for rows.Next() {
		var i GetTransactionsRow
		if err := rows.Scan(
			&i.FirstName,
			&i.LastName,
			&i.Transdatetime,
			&i.Amount,
			&i.Direction,
			&i.Target,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
